name: Checks

on: [pull_request]

jobs:
  readme-md:
    name: README.md check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt

      - name: README check
        run: |
          cd tools
          bash check_readme.sh

  yaspeller:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spell check
        run: |
          npx yaspeller -c .yaspellerrc.json .

  editor-config:
    name: Editor Config check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Editor Config Check
        run: |
          npx eclint check .

  yo:
    name: Ё check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ё checks
        run: |
          npx eyo --only-safe --lint "**/*.md"
